//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.9.7.
// rsrc.rc

#define CMD_NEW                             256
#define CMD_NEW_WINDOW                      257
#define CMD_OPEN                            258
#define CMD_SAVE                            259
#define CMD_SAVE_AS                         260
#define CMD_PRINT                           261
#define CMD_PAGE_SETUP                      262
#define CMD_EXIT                            264
#define CMD_UNDO                            272
#define CMD_CUT                             273
#define CMD_COPY                            274
#define CMD_PASTE                           275
#define CMD_DELETE                          276
#define CMD_SELECT_ALL                      278
#define CMD_TIME_DATE                       279
#define CMD_WRAP                            281
#define CMD_SEARCH                          288
#define CMD_SEARCH_NEXT                     289
#define CMD_REPLACE                         290
#define CMD_GOTO                            291
#define CMD_SEARCH_PREV                     292
#define CMD_HELP_CONTENTS                   304
#define CMD_HELP_ABOUT_NOTEPAD              309
#define CMD_FONT                            320
#define CMD_STATUSBAR                       336
#define CMD_STATUSBAR_WND_ID                337

#define DIALOG_PAGESETUP                    514
#define DIALOG_ENCODING                     516
#define DIALOG_GOTO                         519
#define DIALOG_PRINTING                     523

#define IDC_LICENSE                         522
#define IDC_PRINTING_STATUS                 524
#define IDC_PRINTING_FILENAME               525
#define IDC_PRINTING_PAGE                   526

#define IDI_NPICON                          521

#define ID_ACCEL                            515
#define ID_ENCODING                         517
#define ID_EOLN                             518
#define ID_LINENUMBER                       520

#define MAIN_MENU                           513

#define STRING_PAGESETUP_HEADERVALUE        352
#define STRING_PAGESETUP_FOOTERVALUE        353
#define STRING_NOTEPAD                      368
#define STRING_ERROR                        369
#define STRING_WARNING                      370
#define STRING_INFO                         371
#define STRING_UNTITLED                     372
#define STRING_ALL_FILES                    373
#define STRING_TEXT_FILES_TXT               374
#define STRING_TOOLARGE                     375
#define STRING_NOTEXT                       376
#define STRING_DOESNOTEXIST                 377
#define STRING_NOTSAVED                     378
#define STRING_NOTFOUND                     379
#define STRING_OUT_OF_MEMORY                380
#define STRING_CANNOTFIND                   381
#define STRING_ANSI                         384
#define STRING_UNICODE                      385
#define STRING_UNICODE_BE                   386
#define STRING_UTF8                         387
#define STRING_UTF8_BOM                     388
#define STRING_CRLF                         389
#define STRING_LF                           390
#define STRING_CR                           391
#define STRING_LINE_COLUMN                  392
#define STRING_PRINTERROR                   393
#define STRING_DEFAULTFONT                  394
#define STRING_LINE_NUMBER_OUT_OF_RANGE     395
#define STRING_NOWPRINTING                  396
#define STRING_PRINTCANCELING               397
#define STRING_PRINTCOMPLETE                398
#define STRING_PRINTCANCELED                399
#define STRING_PRINTFAILED                  400
#define STRING_TEXT_DOCUMENT                512
#define STRING_NOTEPAD_AUTHORS              768

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     521
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
