//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.9.7.
// rsrc.rc

#define IDC_NEW                             256
#define IDC_NEW_WINDOW                      257
#define IDC_OPEN                            258
#define IDC_SAVE                            259
#define IDC_SAVE_AS                         260
#define IDC_PRINT                           261
#define IDC_PAGE_SETUP                      262
#define IDC_EXIT                            264
#define IDC_UNDO                            272
#define IDC_CUT                             273
#define IDC_COPY                            274
#define IDC_PASTE                           275
#define IDC_DELETE                          276
#define IDC_SELECT_ALL                      278
#define IDC_TIME_DATE                       279
#define IDC_WRAP                            281
#define IDC_SEARCH                          288
#define IDC_SEARCH_NEXT                     289
#define IDC_REPLACE                         290
#define IDC_GOTO                            291
#define IDC_SEARCH_PREV                     292
#define IDC_HELP_CONTENTS                   304
#define IDC_HELP_ABOUT_NOTEPAD              309
#define IDC_FONT                            320
#define IDC_STATUSBAR                       336
#define IDC_STATUSBAR_WND_ID                337
#define IDC_LICENSE                         522
#define IDC_PRINTING_STATUS                 524
#define IDC_PRINTING_FILENAME               525
#define IDC_PRINTING_PAGE                   526
#define IDC_CYCLIC_REPLACE                  527
#define IDC_GUID                            528
#define IDC_REPLACEMULTIPLEATONCE           529

#define IDD_PAGESETUP                       514
#define IDD_ENCODING                        516
#define IDD_GOTO                            519
#define IDD_PRINTING                        523
#define IDD_FIND                            524
#define IDD_REPLACE                         525
#define IDD_CYCLICREPLACE                   526
#define IDD_ADDITEM                         527
#define IDD_REPLACEMULTIPLEATONCE           528
#define IDD_ADDPAIR                         529

#define IDI_NPICON                          521

#define IDR_MAIN_MENU                       513

#define IDS_PAGESETUP_HEADERVALUE           352
#define IDS_PAGESETUP_FOOTERVALUE           353
#define IDS_NOTEPAD                         368
#define IDS_ERROR                           369
#define IDS_WARNING                         370
#define IDS_INFO                            371
#define IDS_UNTITLED                        372
#define IDS_ALL_FILES                       373
#define IDS_TEXT_FILES_TXT                  374
#define IDS_TOOLARGE                        375
#define IDS_NOTEXT                          376
#define IDS_DOESNOTEXIST                    377
#define IDS_NOTSAVED                        378
#define IDS_NOTFOUND                        379
#define IDS_OUT_OF_MEMORY                   380
#define IDS_CANNOTFIND                      381
#define IDS_ANSI                            384
#define IDS_UNICODE                         385
#define IDS_UNICODE_BE                      386
#define IDS_UTF8                            387
#define IDS_UTF8_BOM                        388
#define IDS_CRLF                            389
#define IDS_LF                              390
#define IDS_CR                              391
#define IDS_LINE_COLUMN                     392
#define IDS_PRINTERROR                      393
#define IDS_DEFAULTFONT                     394
#define IDS_LINE_NUMBER_OUT_OF_RANGE        395
#define IDS_NOWPRINTING                     396
#define IDS_PRINTCANCELING                  397
#define IDS_PRINTCOMPLETE                   398
#define IDS_PRINTCANCELED                   399
#define IDS_PRINTFAILED                     400
#define IDS_INVALID_REGEX                   401
#define IDS_WANTTWOITEMS                    402
#define IDS_CYCLICREPLACEINFO               403
#define IDS_NOTEPAD_VERSION                 404
#define IDS_README                          405
#define IDS_WANTONEITEM                     406
#define IDS_CONFLICT                        407
#define IDS_TEXT_DOCUMENT                   512

#define ID_ACCEL                            515
#define ID_ENCODING                         517
#define ID_EOLN                             518
#define ID_LINENUMBER                       520

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    514
        #define _APS_NEXT_COMMAND_VALUE     521
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
